import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import Background from "@/components/particle-background/background";
import NavigationBar from "@/components/navigation-bar";
import localFont from "next/font/local";
import Footer from "@/components/footer";

const montserratFont = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin"],
});

const neon = localFont({
    src: "../public/fonts/neonlux.ttf",
    variable: "--font-neon",
});

export const metadata: Metadata = {
    title: "Tom Yalda Website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${montserratFont.variable} ${neon.variable} ${montserratFont.className} antialiased`}
            >
                <Providers>
                    <div className="relative h-screen bg-background">
                        <div className="absolute inset-0 z-0">
                            <Background />
                        </div>
                        <div className="relative z-10 h-full grid grid-rows-[auto_1fr_auto]">
                            <header className="sticky top-0 z-30">
                                <NavigationBar />
                            </header>
                            <main className="overflow-y-auto p-8 sm:p-16">
                                {children}
                            </main>
                            <div className="sticky bottom-0 z-30">
                                <Footer />
                            </div>
                        </div>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
