import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/providers";
import Background from "@/components/particle-background/background";
import NavigationBar from "@/components/navigation-bar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Tom Yalda Website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Providers>
                    <div className="relative min-h-screen bg-background">
                        <div className="absolute inset-0 z-0">
                            <Background />
                        </div>
                        <div className="relative z-10">
                            <NavigationBar />
                        </div>
                        <main className="relative z-20 min-h-screen p-8 sm:p-16">
                            {children}
                        </main>
                    </div>
                </Providers>
            </body>
        </html>
    );
}
